name: first-workflow
on: 
  workflow_dispatch:
    branches:
      - main
      - dev
    paths_ignore:
      - '.github/workflows/*'
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: greet
        id: firstjob-id
        run: |
          echo "hello!"
      - name: functions
        if: failure() && steps.firstjob-id.outcome = 'failure'
        run: echo "hi"
